testing individual files

diff --git a/ctest b/ctest
--- a/ctest
+++ b/ctest
@@ -1,13 +1,32 @@
 #!/bin/bash
 
-gcc -Wall -pedantic main.c -lm -o output.out
-PROG="output.out"
-
-if [ -n $1 -a $1 != " " ]
+gcc -Wall -Werror -pedantic main.c -lm -o output.out
+if [ $? -eq 1 ]
 then
-    QUERY="tests/$1_in.txt"
-else
-    QUERY="tests/????_in.txt"
+    exit
+fi
+
+PROG="output.out"
+QUERY="tests/????_in.txt"
+
+if [ $# -ne 0 ]
+then
+    QUERY=""
+    for ARG in $@
+    do
+        if [ $ARG -lt 10 ]
+        then
+            ARG="000$ARG"
+        elif [ $ARG -lt 100 ]
+        then
+            ARG="00$ARG"
+        elif [ $ARG -lt 1000 ]
+        then
+            ARG="0$ARG"
+        fi
+
+        QUERY="$QUERY"" ""tests/""$ARG""_in.txt"
+    done
 fi
 
 for INPUT in $QUERY
@@ -15,27 +34,35 @@ do
     INPUT_FILENAME=`basename $INPUT` &&
     OUTPUT_FILE=tests/${INPUT_FILENAME:0:4}_out.txt
 
-    ./$PROG < $INPUT > output.txt
-
-    TEST=$(diff $OUTPUT_FILE output.txt)
-    if [ $? -eq 0 ]
+    if [ -f $INPUT ]
     then
-        tput setaf 2
-        tput bold
-        echo "${INPUT_FILENAME:0:4}: Success"
-        tput sgr0
+        O=$( ./$PROG < $INPUT )
+
+        TEST=$(diff -y --color=always $OUTPUT_FILE <( echo "$O" ))
+        if [ $? -eq 0 ]
+        then
+            tput setaf 2
+            tput bold
+            echo "${INPUT_FILENAME:0:4}: Success"
+            tput sgr0
+        else
+            tput setaf 1
+            tput bold
+            echo -e "${INPUT_FILENAME:0:4}: Failed"
+            tput sgr0
+            tput bold
+            echo "Input:"
+            tput sgr0
+            echo -e "$( cat $INPUT )\n"
+            tput bold
+            echo "Error in:"
+            tput sgr0
+            echo -e "$TEST\n"
+        fi
     else
         tput setaf 1
         tput bold
-        echo -e "${INPUT_FILENAME:0:4}: Failed"
+        echo "${INPUT_FILENAME}: Missing input file"
         tput sgr0
-        tput bold
-        echo "For input:"
-        tput sgr0
-        echo -e "$( cat $INPUT )\n"
-        tput bold
-        echo "Error in:"
-        tput sgr0
-        echo -e "$TEST\n"
     fi
 done
